### ISSUE TITLE
Dnsmasq does not bind to AP interface 

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#109]
PR #106 
for some reason dnsmasq does not bind to 10.0.0.1 on boot, but it does after a restart on orange pi in branch.
adding service dnsmasq restart in /etc/rc.local "fixes" it

**Comment by benhylau** [comment]
Is there a fix to this in already?

**Comment by darkdrgn2k** [comment]
seems it was just a corrupt interface file fixed in #111
