### ISSUE TITLE
prometheus-node-exporter Rename

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#128]
prometheus-node-exporter is long (esp in the readme)
the program is just called node-exporter

perhaps drop the prometheus part, we don't do prometheus-grafana 

thoughts?

**Comment by benhylau** [comment]
But node-exporter is part of Prometheus, from what I understand. Grafana is a separate project.

**Comment by darkdrgn2k** [comment]
Yeh its more of a cosmetic thing to not have a 50 letter flag in the readmes and such.

Close the issue if you like or tell me and ill make the necessary changes.

Really I'm impartial. Your Call:)

**Comment by benhylau** [comment]
To not deviate from the convention (since prometheus-server has the prometheus in there), and node-exporter being too generic of a name, I think we should keep as is.
