### ISSUE TITLE
Cannot uninstall IPFS data directory

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi#138]
Received report that ipfs uninstall does not find `~/.ipfs` until changed to:

```
if [ -d "$HOME/.ipfs" ]; then
```

And then:

>rm: cannot remove '/home/pi/.ipfs/blocks/...

Owned by root user. Possibly related to https://github.com/tomeshnet/prototype-cjdns-pi/issues/112

**Comment by darkdrgn2k** [comment]
Might be wise to rewrite the install script to run IPFS as its own user?

**Comment by makeworld-the-better-one** [comment]
This has been fixed in #179 . The solution was just to use sudo rm, which doesn't actually change the home directory.

**Comment by darkdrgn2k** [comment]
Service should be re-worked to actually run as pi user not root and put files in pi directory. But for now closing.
