### ISSUE TITLE
Update documentation for Pi 3 B+ support

### ISSUE THREAD

**Issue by skylarmt** [tomeshnet/prototype-cjdns-pi#142]
Is the Pi 3 B+ supported?

**Comment by darkdrgn2k** [comment]
Sorry for the delay in responding to this issue. Yes i have tested it and it works. It is also slightly faster then the pi3 B+. 

I have not had time to really test the board so please let us know your results.

I'd suggest using [develop-bata](https://github.com/tomeshnet/prototype-cjdns-pi/tree/develop-beta) branch. I have already added detection for PI 3b+ into it

```
$ wget https://raw.githubusercontent.com/tomeshnet/prototype-cjdns-pi/develop-beta/scripts/install && chmod +x install && TAG_PROTOTYPE_CJDNS_PI=develop-beta ./install
```

**Comment by darkdrgn2k** [comment]
#141 merged into the Develop now  and slated for Version 2

@skylarmt any more issues or can we close.

**Comment by skylarmt** [comment]
Nothing else, the code itself worked fine when I tried it before your commits, the issue was mostly about documentation.
