### ISSUE TITLE
Duplicate peer-ipfs-bootstrap

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi#167]
@makeworld-the-better-one Please check your PR, this code is in two places and the script references are incorrect.

See:
https://github.com/tomeshnet/prototype-cjdns-pi/pull/163
https://github.com/tomeshnet/prototype-cjdns-pi/tree/develop/scripts/peer-ipfs-bootstrap

`install2` should not directly reference this. The ipfs `install` is responsible for running this. Same with `uninstall` scripts.

**Comment by makeworld-the-better-one** [comment]
Ah sorry, I'll fix that. I had one last unpushed commit that I thought was a mistake. Thanks for catching that!

**Comment by benhylau** [comment]
Thanks!

**Comment by makeworld-the-better-one** [comment]
I've removed the duplicate folder and fixed `install2` and `uninstall`.
