### ISSUE TITLE
IPTunnel - nodejs does not run under udev on some computers

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#175]
Possible issues on some devices running nodejs (cexec) via udev

https://github.com/nodejs/node/issues/19036

https://github.com/nodejs/node/issues/16901

**Comment by benhylau** [comment]
How may this affect us? The cjdns compilation?

**Comment by darkdrgn2k** [comment]
@ASoTNetworks ran into this bug on a computer (not SBC) when trying to create an exit node using iptunnel.

`cexec` uses nodejs, which had an issue executing. He found the above mentioned bugs.

Script not executing properly
https://github.com/tomeshnet/prototype-cjdns-pi/blob/master/scripts/cjdns-iptunnel/cjdns-setup

Running it manually after the fact brought the configuration up without a problem just not in the udev environment

**Comment by darkdrgn2k** [comment]
On debian node crashes when run in udev env

```
root@exit1:/home/user# nodejs --version
v8.12.0
```
```
[1907700.743443] node[11729]: segfault at f ip 0000000000fe8280 sp 00007ffd8f3d72a0 error 6 in node[400000+1b60000]
```
works fine when run out of  uden env

**Comment by darkdrgn2k** [comment]
possible work around

Add this 
`ExecStartPost=/usr/local/sbin/cjdns-setup`
to

`/etc/systemd/system/cjdns.service`

then run
 `sudo systemctl daemon-reload`
