### ISSUE TITLE
Force password reset on pi

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#198]
Force the pi user to reset the password on first login after install reboot? 

Expires pi users password
```
sudo passwd -e pi
```

**Comment by jedahan** [comment]
First boot experience vs. security tradeoff.
If the expiration is presented as "Please choose a password!" then it empowers the user and improves security.
If the expiration also works fine via ssh / headless then 👍

**Comment by darkdrgn2k** [comment]
armbian does this on first boot of the device on first login ssh or console

I think adding it to the rpi after first boot makes sense since it could be connected to the public hyperborea at that time
