### ISSUE TITLE
Nginx installation

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#248]
~~Nginx right now installes for IPFS and some SSB modules~~

~~Should it always be installed? It serves.~~
~~ - Welcome page~~
~~ - nodeinfo.json~~

~~also~~

~~- [ ] Add check if its installed before trying to write to it~~

- [x] Remove shared installation of nginx from modules
- [x] Move nginx from shared folder to main modules 
- [x] Install nginx as part of install script (unasked module)

**Comment by makeworld-the-better-one** [comment]
I would say it should, especially with the new welcome page. It wouldn't be uncommon for someone not to install IPFS and SSB, but to want be able to see the welcome page with the node graphs. And nodeinfo.json is helpful.

**Comment by benhylau** [comment]
I think nginx should be default installation

**Comment by darkdrgn2k** [comment]
C/P from https://github.com/tomeshnet/prototype-cjdns-pi/pull/252#discussion_r243927639

@benhylau 
So which are we doing?

    nginx in shared
    classify into default vs. optional
    Leave nginx in root like cjdns

**Comment by makeworld-the-better-one** [comment]
I would get rid of `shared`, and move `nodeinfo` out of it, switching to an `optional` vs `default` setup. I also think CJDNS should be moved out of the script and into it's own module, in the `default` folder.
