### ISSUE TITLE
Raspbian Stretch Lite, Windows, & Virtual Machine?

### ISSUE THREAD

**Issue by ForgivenNin** [tomeshnet/prototype-cjdns-pi#258]
As far as I know, the Raspbian Stretch Lite OS is just pure terminal (if you get what I'm saying); and I was wondering if there are any other operating systems that are so far compatible. This is because I had other ideas for my pi along with connecting to the meshnet.

Maybe another option is that one could use the windows operating system that comes along with NOOBS and then follow the setup that the original cjdns is built around.

Also, what if one tried doing this through a virtual machine? I am not very tech savy, but what do you think if somebody also tried testing their connection to the meshnet with Linux Kali?

_(If the owner of this prototype is reading this, thank you so much for taking the time to make this!)_

**Comment by darkdrgn2k** [comment]
Hi @ForgivenNin 

First let me say if you want a longer real-time dialog about anything mesh we usually sit on this [matrix chat](https://chat.tomesh.net/#/room/#tomesh:tomesh.net) also accessible via IRC at #tomesh on freenode.

All the code in the prototype script is geared towards ARM boards (and arm64) as "router boards".  This means it SHOULD work on any debian/ubuntu system running on an ARM capable board.

Raspbian Stretch - Desktop should work with this model too, however there are no "desktop gui" components in our package so we opt out to save ram and such 

(Also we support few other boards such as the Orange Pi family running [Armbian](http://armbian.com).  Adding additional support for other Arabian boards proved to be trivial)

If you want to buy an inexpensive board to poke at the [Orange Pi Zero](https://www.aliexpress.com/item/New-Orange-Pi-Zero-H2-Quad-Core-Open-source-512MB-development-board-beyond-Raspberry-Pi/32761500374.html)  is the cheapest board i have seen. **NOTE** this is *NOT* the Raspberry pi Zero. 

We currently don't have implementation for i386 although it could be added.  For the most part its just about pulling the right packages. It should not be to hard to add support for that.

Windows is a different beat completely and the script would not work at all. 
However:
 - If you build a raspberry pi (3b or better) as a node, you can access if via the WiFi access point it creates you will have access to all the resources of CJDNS and Yggdrasil on your windows/mac or other based PC
 - You can install the individual components on your windows machine to access those resources as well.

I have been meaning to play with terraform and VirtualBox, maybe when i get that going i can get a platform to add support for i386 boards.
