### ISSUE TITLE
Hostapd network scan fails

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#282]
`for wlan in $(find /sys/class/net -maxdepth 1 -name 'wlan*' | xargs -0 basename); do`

line only return first result instead of all of them

**Comment by makeworld-the-better-one** [comment]
What is this used for?

**Comment by darkdrgn2k** [comment]
To clarify

the folder `/sys/class/net` contains all the network interfaces

`/sys/class/net/$wlan/device/driver` is a SYMLINK to the driver it uses

`readlink` will output the path to the symlink target
`basename` will output the filename in a path yeidling the driver for the interface

currently the for loop should iterate through all WLANx but it only does the first one

**Comment by makeworld-the-better-one** [comment]
Can we just disable shellcheck for that area?

**Comment by darkdrgn2k** [comment]
we could
but we should probably devise a better line.

Shell check comments are valid.

**Comment by darkdrgn2k** [comment]
Interesting read on bash scripting and for loops

https://mywiki.wooledge.org/BashPitfalls#pf1

Simpler loop solution
```
for wlanfile in /sys/class/net/wlan*; do
    wlan="$(basename "$wlanfile")"
```
