### ISSUE TITLE
Develop branch install ends abruptly

### ISSUE THREAD

**Issue by dasanchez** [tomeshnet/prototype-cjdns-pi#286]
The installation process ends abruptly with the following line if yggradsil is selected as an option:
```
usermod: group 'yggdrasil' does not exist
```
This was using the _develop_ branch, as of 2019-Feb-9.
```
wget https://raw.githubusercontent.com/tomeshnet/prototype-cjdns-pi/develop/scripts/install && chmod +x install && TAG_PROTOTYPE_CJDNS_PI=develop ./install
```

![ygg](https://user-images.githubusercontent.com/2331903/52534794-f20bd100-2d13-11e9-8986-4dad1968163e.PNG)

**Comment by darkdrgn2k** [comment]
That line was moved into nginx.  

Either i forgot to remove it or it came back in one of the prs.

Thanks for spotting, should be good now.

**Comment by makeworld-the-better-one** [comment]
Can this be closed?

**Comment by dasanchez** [comment]
@makeworld-the-better-one let's make sure the issue goes away.
I'm reflashing the node now. I tried running the install off develop after running the uninstall script from master and I got this:
![node-exporter](https://user-images.githubusercontent.com/2331903/52605505-2202c380-2e3d-11e9-94db-911c8932cdaf.PNG)

**Comment by darkdrgn2k** [comment]
Uninstalls is horrible :( reflash is better ;)

Ok i patched that error. let see if there are any more

**Comment by makeworld-the-better-one** [comment]
I'm going to close the issue, since this specific one is gone. The develop branch does need to be tested, but we can share results in chat.
