### ISSUE TITLE
Trouble shooting doc

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#334]
Quick braindump of troubleshooting steps, Needs to be put into a better formated documents

# Wireless Meshing

## ISBB
- `iw dev` do all the pis have matching BSID and channels
- `iw wlan0 station dump` does it show stations (negative result may not mean problem some drivers just wont show anything. Onboard pi driver is one of these that will not show anything)
- `sudo /usr/bin/mesh-adhoc`  - does it return any errors
   - `sudo bash -x  /usr/bin/mesh-adhoc`  - if errors this should show where it occurs
- if you set an IP  address on wlan0 on both sides, can it ping in the clear

## Mesh Point
- `iw dev` do all the pis have matching channels (BSID will not show)
- `cat /usr/bin/mesh-mesh` is the JOIN line have the correct mesh name
- `iw wlan0 station dump` does it show stations
- `sudo /usr/bin/mesh-point`  - does it return any errors
   - `sudo bash -x  /usr/bin/mesh-point`  - if errors this should show where it occurs
- if you set an IP  address on wlan0 on both sides, can it ping in the clear

# IPTunnel general
- can client node ping cjdns/yggdsaill address of exit node
- can exit node access the internet
- can client node ping an ip address (not DNS)

# IPTUNNEL - cjdns
- is iptunnel installed (/usr/local/sbin/cjdns-setup exists)
- is the cjdns.iptunnel.server/client filename correct and on the correct device
- are the keys correct (ends in a k)
- does `tun0` have a ipv4 ipaddress on server
- does `tun0` have ipv4 address on client
- can you ping the ipv4 addresses across the tunnel
- does masuqarade line in `iptables -L -v -n -t nat` exist
- does masuqarade line in `iptables -L -v -n -t nat` show the right out interface

# IPTUNNEL - yggdrasil
- is iptunnel installed (/usr/local/sbin/yggdrasil-setup exists)
- is the yggdrasil.iptunnel.server/client filename correct and on the correct device
- are the keys correct (64 character alpha numeric)
- does `ygg0` have ipv4 address on client
- can you ping the ipv4 addresses from the server
- does masuqarade line in `iptables -L -v -n -t nat` exist
- does masuqarade line in `iptables -L -v -n -t nat` show the right out interface

**Comment by makeworld-the-better-one** [comment]
I would like to add something about netcat in here as well, pointing users to installing `netcat-openbsd`on their computer if netcat isn't working for them.
