### ISSUE TITLE
Add SSB announce of pub 

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#349]
https://github.com/ssbc/docs/blob/master/scuttlebot/howto-announce-a-pub-server.md

**Comment by darkdrgn2k** [comment]
Need more explenation what this actaully does.

Seems to be added to clients when they are added to a pub to announce the existence of the pub.

**Comment by makeworld-the-better-one** [comment]
Asked about it on Scuttlebutt [here](https://viewer.scuttlebot.io/%25WdTNUN7dJ01MWgXT%2B868NdsA25SvJt7ZTIhnDWQKqXI%3D.sha256). The hash is `%WdTNUN7dJ01MWgXT+868NdsA25SvJt7ZTIhnDWQKqXI=.sha256`, and I tagged you @darkdrgn2k.

**Comment by makeworld-the-better-one** [comment]
As discussed in chat, this is likely not needed for our nodes to do. Clients will do this automatically.

**Comment by darkdrgn2k** [comment]
Pubs already announced during each used invite.

No need for more announcements.
