### ISSUE TITLE
Put systemd files in one consistent place

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi#35]
systemd `*.service` files are placed in both:

    /lib/systemd/system/
    /etc/systemd/system/

Put them in one consistent place.

**Comment by darkdrgn2k** [comment]
> Basically, files that ships in packages downloaded from distribution repository go into /usr/lib/system/. Modifications done by system administrator (user) go into /etc/systemd/system/. System-specific units override units supplied by vendor. Using drop-ins, you can override only specific parts of unit file, leaving rest to vendor (drop-ins are available since the very beginning of systemd, but were properly documented only in v219; see man systemd.unit).

From what i read we should put them in /etc/systemd/system not /lib as these are not packages.

**Comment by benhylau** [comment]
Consistent with what I have read earlier. Thanks!
