### ISSUE TITLE
hostapd does not set SSID properly

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#365]

**Comment by makeworld-the-better-one** [comment]
Can you elaborate? What does it set it to?

**Comment by darkdrgn2k** [comment]
Noticed that hostapd didnot set ssid in ygg-tunnel-ipv6

Issue found to be ssid derived from cjdns when cjdns  did not exist
Fixed in 19e64b03764f78fe14af28658235c45cf7678238
