### ISSUE TITLE
Migrate hostname and meshname to config

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#368]
- [x] https://github.com/tomeshnet/prototype-cjdns-pi/blob/develop/scripts/hostapd/install#L48
- [x] https://github.com/tomeshnet/prototype-cjdns-pi/blob/develop/scripts/install2#L409
- [x] https://github.com/tomeshnet/prototype-cjdns-pi/blob/develop/scripts/cjdns/install#L126
- [x] https://github.com/tomeshnet/prototype-cjdns-pi/blob/develop/scripts/yggdrasil/install#L65
- [x] https://github.com/tomeshnet/prototype-cjdns-pi/blob/develop/scripts/install2#L402

**Comment by makeworld-the-better-one** [comment]
Are you referring to the config file referenced in #319? Might be better to put those links there instead of having the separate issue, since we still would need to figure that out before we do this.

**Comment by darkdrgn2k** [comment]
Yes,

Currently there is a dependency in some modules that require a host name to have a global variable set. So if you manually install (for example) hostapd, it will not set the configure correctly because the hostname was set in a different module

Using a common config file allows us to remove the need for having this dependency and instead rely on a single file.

hostname and mesh name are the two variables im aware of that right now need global variables set.

**Comment by makeworld-the-better-one** [comment]
Yeah that makes sense, thanks for outlining these places.

**Comment by darkdrgn2k** [comment]
All done
