### ISSUE TITLE
Espressobin  br0 instead of eth0

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#370]
EspressoBIN uses br0 not eth0 for its networking

https://github.com/tomeshnet/prototype-cjdns-pi/blob/ygg-tunnel-ipv6/scripts/install2#L81

**Comment by makeworld-the-better-one** [comment]
Can we use board detection and change the commands accordingly? `eth0` is used 4 times in that script, so there could also be variable set for it.

**Comment by darkdrgn2k** [comment]
yeh eth0 need to be a. variable set based on output of boardinfo

but should also be configurable later via config/gui

**Comment by simplymathematics** [comment]
Can solve this one when my oi comes in a week or two!
