### ISSUE TITLE
ipfs-pi-stream assumes a username of pi

### ISSUE THREAD

**Issue by makeworld-the-better-one** [tomeshnet/prototype-cjdns-pi#413]
In [`scripts/ipfs-pi-stream/process-stream.service`](https://github.com/tomeshnet/prototype-cjdns-pi/blob/develop/scripts/ipfs-pi-stream/process-stream.service), the user and group `pi` are mentioned, which won't work on devices other than the Raspberry Pi. Maybe this could be edited during install using `sed` or something?

**Comment by darkdrgn2k** [comment]
Pi stream **ONLY** works on raspberry pi devices due to the camera requirement.

**Comment by makeworld-the-better-one** [comment]
Ah of course, my bad.
