### ISSUE TITLE
Pi Stream STATUS

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#415]
Using `ffmpeg` for detection of PI STREAM installation is not a good way to deal with it. Pi Desktop also installs ffmpeg by default returning a false positive.

https://github.com/tomeshnet/prototype-cjdns-pi/blob/master/scripts/status#L75

**Comment by makeworld-the-better-one** [comment]
You could check for the `process-stream.service` file maybe?

**Comment by darkdrgn2k** [comment]
that is checked for "active/inactive" and checking for an installed file is used for checking if its installed.
