### ISSUE TITLE
STATUS script - create Module

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#416]
Create a plug-able system for ~~PI STREAM~~ Status

Create for a method to have each module drop a file into a folder that would get executed by STATUS for each module

This way each module can define its own status mechanism instead of depending on a file that has the info for ALL the modules in one as we do now

See nodeinfo module for example

**Comment by makeworld-the-better-one** [comment]
Allowing for what? Different camera streams?

**Comment by darkdrgn2k** [comment]
I mis spoke in original comment, corrected.

**Comment by darkdrgn2k** [comment]
Duplicate of #380
