### ISSUE TITLE
hostapd doesnt set ssid due to new hostname method

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#418]

**Comment by makeworld-the-better-one** [comment]
Can you elaborate on this, showing the lines of code? Maybe there should be a fallback to the current hostname?

**Comment by darkdrgn2k** [comment]
Observational note of things to investigate.

Seems to be fixed by moving hostname higher in the install process (just after the routing/ip assignments) 681be636ea0f99e32ef319e5a33d8f17f2a3ae02 and 9f3f4e2c279ea3cb3ebaf11eb088af097362f7e5 (that was was accidentally committed right to the dev branch
