### ISSUE TITLE
Link to Pine64 Armbian build is broken

### ISSUE THREAD

**Issue by dasanchez** [tomeshnet/prototype-cjdns-pi#422]
The link to the nightly builds for Pine64 in the README is broken:

https://dl.armbian.com/pine/nightly/
should probably be
https://dl.armbian.com/pine64/nightly/

**Comment by dasanchez** [comment]
The Build a Node Page still points to this link for the Pine image:
https://dl.armbian.com/pine/nightly/

**Comment by benhylau** [comment]
Should be fixed by https://github.com/tomeshnet/prototype-cjdns-pi/pull/443
