### ISSUE TITLE
Hostapd Automatic Channel Selection

### ISSUE THREAD

**Issue by leosan902** [tomeshnet/prototype-cjdns-pi#452]
Where is the config file to change this configuration?
CONFIG_ACS=y
That is needed to enable Automatic Channel Selection,
documentaion:
https://gitlab.gwdg.de/eap-saml/hostapd/blob/master/src/ap/acs.c
https://wireless.wiki.kernel.org/en/users/documentation/acs

**Comment by darkdrgn2k** [comment]
Seems to be a HOSTAPD thing

```
# If CONFIG_ACS build option is enabled, the channel can be selected
# automatically at run time by setting channel=acs_survey or channel=0, both of
# which will enable the ACS survey based algorithm.
```

CONFIG_ACS is a BUILD OPTION which means it needs to be part of the parameters when compiled.  Im not sure what debian/ubuntu use for their flags when building their packages.

If they do not have it enabled, then you must re-compile hostapd from source and make sure the flag is set.

**Comment by leosan902** [comment]
And my alfa network that i'm using as a AP doesnt have this drivers
ath5k
ath9k 
ath10k

**Comment by darkdrgn2k** [comment]
Not sure what board and distro your running this on.  Or which wifi card you are running.

note: out-of-the-box prototype does not have a way of using anything but the onboard wifi for access point (although can be manually hacked into place)
