### ISSUE TITLE
ASUS USB-N14 seems to cause interface enumeration confusion (again)

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi#54]
**ASUS USB-N14** (used as Mesh Point interface) seems to make the access point not come up properly unless it is plugged in a few seconds after boot. Probably some variation of https://github.com/tomeshnet/prototype-cjdns-pi2/issues/20

**Setup:**
- Pi 3
- ASUS USB-N14
- Backhauled by a 3G connection

**Comment by benhylau** [comment]
cc. @stigtsp

**Comment by darkdrgn2k** [comment]
May be solved with modifications in #87 as it now has better phy to WLAN check

**Comment by darkdrgn2k** [comment]
New mesh setup scripts no longer care about phy vs interface
#89 would solve the issue

**Comment by darkdrgn2k** [comment]
to lock WLAN? location by mac

create a file /etc/udev/rules.d/10-network-device.rules

SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="12:42:0d:80:70:50", NAME="wlan0"
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="8c:88:2b:00:00:0a", NAME="wlan1"
SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="8c:88:2b:00:00:03", NAME="wlan2"

**Comment by darkdrgn2k** [comment]
Even without rules.d this should not longer be a problem since we fixed the mesh script and we pin the Ap onboard adapter as wlan-ap by Mac address on boot.

Just need to confirm this is the case.. Still have the USB to test?

**Comment by benhylau** [comment]
I don't think @stigtsp still has that USB. Let's close this and re-open if we encounter this again with other devices.
