### ISSUE TITLE
Change References of Pi2 to Pi

### ISSUE THREAD

**Issue by garrying** [tomeshnet/prototype-cjdns-pi#57]
Looks like we have most available Pis covered. We should rename the `TAG_PROTOTYPE_CJDNS_PI2` to `TAG_PROTOTYPE_CJDNS_PI` and consider renaming the repo.

**Comment by benhylau** [comment]
I was thinking that too, but all the documents and slides. That's why I want to keep the installation line (i.e. `install` filename) unchanged.

**Comment by benhylau** [comment]
@garrying so... what to do about this? I am not strongly against changing the name and breaking all docs referencing this.

**Comment by garrying** [comment]
@benhylau I think we should move forward on this. Changing refs in docs sounds like a quick follow-up.

**Comment by benhylau** [comment]
#67
