### ISSUE TITLE
MSS Clamping

### ISSUE THREAD

**Issue by ansuz** [tomeshnet/prototype-cjdns-pi#64]
I had some issues reaching a few websites. @cjdelisle suggested this line of code to fix MSS clamping:

`iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --clamp-mss-to-pmtu`

The issue generally seems resolved after that, but since I haven't added it to any scripts, I have to run whenever the pi reboots.

**Comment by benhylau** [comment]
See this for an explanation on this magical incantation: http://lartc.org/howto/lartc.cookbook.mtu-mss.html

**Comment by benhylau** [comment]
#67
