### ISSUE TITLE
Entropy

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi#72]
Install `haveged`

**Comment by darkdrgn2k** [comment]
seems easy enough

orange pi already has it as part of armbian
apt-get install haveged (on stretch)

**Comment by benhylau** [comment]
So if we just install this on all supported platforms as part of `install2` how do we know if it's working? Does it require any configuration?

**Comment by benhylau** [comment]
De-scope from next release. Not critical to Stretch support.

**Comment by darkdrgn2k** [comment]
Q: can you check if haveged is working

A: You can 
```
cat /dev/random | openssl end -e -base64
```
if it hangs, it's definitely not working, if it continuously prints stuff, it's probably working
